name: "Build and publish Python sdist"

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Deployment target. Can be "pypi" or "testpypi"'
        default: 'pypi'
  workflow_run:
    workflows: ["Build and publish Python wheels"]
    types: [completed]

jobs:
  # If build_wheels fails, exit this workflow
  exit-workflow:
    name: Exit workflow if build_wheels fails
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: exit 1


  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    if: |
      ${{ github.event.workflow_run.conclusion == 'success' }} ||
      github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install wheel

      - name: Build sdist
        run: python setup.py sdist --formats=gztar

      - name: Upload sdist
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: ./dist/*.tar.gz
          if-no-files-found: error


  publish-pypi:
    name: Upload sdist to PyPI
    needs: build_sdist
    runs-on: ubuntu-latest
    steps:
      - name: Download sdist
        uses: actions/download-artifact@v2
        with:
          name: files
          path: sdist

      - name: Publish sdist on PyPI
        if: |
          github.event.inputs.target == 'pypi' ||
          (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
          ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: sdist/

      - name: Publish sdist on TestPyPI
        if: github.event.inputs.target == 'testpypi'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_TOKEN }}
          packages_dir: sdist/
          repository_url: https://test.pypi.org/legacy/
